version: "3.9"

services:
    app:
        build:
            context: .
        image: dteam-app:latest
        container_name: dteam-app
        ports:
            - "8080:8080"
        environment:
            APP_NAME: Laravel
            APP_ENV: production
            APP_KEY: "base64:L6YNpQ10XM5MT/Hc3fzNo4GQldXKg+YvHouKlrGNy6U="
            APP_DEBUG: "true"
            APP_URL: "http://localhost:8080"

            LOG_CHANNEL: stack
            LOG_LEVEL: info

            DB_CONNECTION: mysql
            DB_HOST: "34.101.140.103"
            DB_PORT: "3306"
            DB_DATABASE: dteam
            DB_USERNAME: jasondt11
            DB_PASSWORD: "Jasondt151!"

            CACHE_DRIVER: file
            SESSION_DRIVER: file
            QUEUE_CONNECTION: sync

            MAIL_MAILER: smtp
            MAIL_HOST: smtp.gmail.com
            MAIL_PORT: "587"
            MAIL_USERNAME: dteamslc@gmail.com
            MAIL_PASSWORD: "czer ojen exze vkxi"
            MAIL_ENCRYPTION: tls
            MAIL_FROM_ADDRESS: dteamslc@gmail.com
            MAIL_FROM_NAME: "DTeam Admin"

        restart: unless-stopped
